version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./dist/:/usr/share/nginx/html
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  backend:
    image: lordtrua/gwshttp
    container_name: backend
    depends_on:
      - "db"
    ports:
      - "8080:80"
    networks:
      - backend-net

  db:
    image: graddb
    container_name: database
    environment:
      POSTGRES_DB: "GraduateWork"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
