version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./dist/:/usr/share/nginx/html
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
